language: android
jdk: oraclejdk8
sudo: true
cache: false
android:
	components:
		- platform-tools
		- build-tools-25.0.2
		- android-25
		- extra-android-m2repository
before_install:
	- chmod +x gradlew
branches:
	only:
		- master
script:
	- ./gradlew clean build -PdisablePreDex
