language: android
sudo: required
jdk: oraclejdk7
android:
	components:
		- platform-tools
		- build-tools-25.0.2
		- android-25
		- extra-android-m2repository
script:
	- ./gradlew clean build
before_install:
	- chmod +x gradlew
branches:
	only:
		- master
